import 'dart:convert';
import 'dart:typed_data';

// 独立编码样本：Pillow 12.3.0 生成，80x48 自制象限/灰阶图。
// 不含用户图片；用于覆盖渐进 JPEG、CMYK、调色板和 16 位 PNG。

Uint8List progressiveJpeg() => base64Decode(
  '/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAEBAQEBAQEBAQEBAQEBAQIBAQEBAQIBAQECAgICAgICAgIDAwQDAwMD'
  'AwICAwQDAwQEBAQEAgMFBQQEBQQEBAT/2wBDAQEBAQEBAQIBAQIEAwIDBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQE'
  'BAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAT/wgARCAAwAFADASIAAhEBAxEB/8QAFwABAQEBAAAAAAAAAAAAAAAA'
  'AAkIB//EABgBAQEBAQEAAAAAAAAAAAAAAAAJCAcK/9oADAMBAAIQAxAAAAHK4zXbgBuTDe5OexzDnscwMNuwKrev'
  'bj7sA4/uTPdjMXzynuoQxfPKe6hAjmPTlfgBYyOdjJQ5xCUOcQP/xAAUEAEAAAAAAAAAAAAAAAAAAABQ/9oACAEB'
  'AAEFAnP/xAAyEQAAAAcLDQAAAAAAAAAAAAAACBASExRjAwcJERUYZqKk4eQWFyEkQUNFRmKDhcPF/9oACAEDAQE/'
  'ASQs/IHlfmll9lWuCX2Va4B9Hq89GSmvqamvbpMemU2jkaai6oztkWmZxSOyYoJnFI7JiijAcJ7/AKS//8QAMREA'
  'AAAHDAsAAAAAAAAAAAAAAAYQEhMUFwMICREYYmRmo6Ti5BYhJEFCREaChcLF/9oACAECAQE/ASD5yvf6Fkg1humZ'
  'CSDWG6ZkH3ghML0e2tdXVvgQGIFae7HHJpsRu+PU0Oh2mAGh0O0wFhPeiPJfPL//xAAUEAEAAAAAAAAAAAAAAAAA'
  'AABQ/9oACAEBAAY/AnP/xAAUEAEAAAAAAAAAAAAAAAAAAABQ/9oACAEBAAE/IXP/2gAMAwEAAgADAAAAEAAAAAAA'
  'AAAAAAAAP//EABQRAQAAAAAAAAAAAAAAAAAAADD/2gAIAQMBAT8QcFVhABCq/wD/xAAUEQEAAAAAAAAAAAAAAAAA'
  'AAAw/9oACAECAQE/EHbd5qmWEW//xAAUEAEAAAAAAAAAAAAAAAAAAABQ/9oACAEBAAE/EHP/2Q==',
);

Uint8List cmykJpeg() => base64Decode(
  '/9j/7gAOQWRvYmUAZAAAAAAA/9sAQwABAQEBAQEBAQEBAQEBAQECAQEBAQECAQEBAgICAgICAgICAwMEAwMDAwMC'
  'AgMEAwMEBAQEBAIDBQUEBAUEBAQE/8AAFAgAMABQBEMRAE0RAFkRAEsRAP/EAB8AAAEFAQEBAQEBAAAAAAAAAAAB'
  'AgMEBQYHCAkKC//EALUQAAIBAwMCBAMFBQQEAAABfQECAwAEEQUSITFBBhNRYQcicRQygZGhCCNCscEVUtHwJDNi'
  'coIJChYXGBkaJSYnKCkqNDU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6g4SFhoeIiYqSk5SV'
  'lpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2drh4uPk5ebn6Onq8fLz9PX29/j5+v/aAA4E'
  'QwBNAFkASwAAPwD+4Cv4n6/ifr+/iiiiiiiiiiiiiiiiiv8AEfr/AGkKKKKKKKKKKKKKKKKKKK/24K/xb6KKKKKK'
  'KKKKKKKKKKKK/wAR+v8AaQoooooooooooooooooor/bgr/Fvoooooooooooooooooor/ABH6/wBpCiiiiiiiiiii'
  'iiiiiiiv9uCv8W+v9pCiiiiiiiiiiiiiiiiiiv8AaQr/ABb6KKKKKKKKKKKKKKKKKK/xb6/2kKKKKKKKKKKKKKKK'
  'KKKK/wBpCv8AFvoooooooooooooooooor/Fvr/aQoooooooooooooooooor/AGkK/wAW+iiiiiiiiiiiiiiiiiv/'
  '2Q==',
);

Uint8List palettePng() => base64Decode(
  'iVBORw0KGgoAAAANSUhEUgAAAFAAAAAwAgMAAAD7ixVkAAAADFBMVEXw5hQU5hTwFObwFBRF9VD1AAAAKUlEQVR4'
  'nGP8zwADYXAWEwMWwDQqOIwChGU1nIlgDUJ3Mo0KogIKAwQAmKMDDYrNDbEAAAAASUVORK5CYII=',
);

Uint8List grayscalePng() => base64Decode(
  'iVBORw0KGgoAAAANSUhEUgAAAFAAAAAwEAAAAADzHn5oAAAAY0lEQVR4nM3OMQEAMAyAMIbySp+EniUK8oY2iZM4'
  'iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4iZM4'
  'rwObD9/cAODuB+QhAAAAAElFTkSuQmCC',
);
