Map<String, Object?> postEditedTimeJson({
  String id = 'floor',
  bool reply = false,
  Object? editedAt,
  bool includeEditedAt = true,
}) => {
  'id': id,
  'threadId': 'thread',
  'subthreadId': 'subthread',
  'authorId': 'author',
  'kind': 'FLOOR',
  'floorNumber': reply ? null : 7,
  'parentPostId': reply ? 'floor' : null,
  'content': reply ? '回复正文' : '楼层正文',
  'diceRolls': <Object>[],
  'version': 9,
  'createdAt': '2024-01-01T02:00:00.000Z',
  'updatedAt': '2026-09-29T02:00:00.000Z',
  if (includeEditedAt) 'editedAt': editedAt,
  'author': {'id': 'author', 'username': '作者', 'level': 2},
  '_count': {'replies': reply ? 0 : 1},
  'replies': <Object>[],
  'thread': {'id': 'thread', 'title': '主题'},
  'subthread': {'id': 'subthread', 'title': '子贴'},
  if (reply) 'parentPost': {'id': 'floor', 'floorNumber': 7},
};
