// GENERATED CODE - DO NOT MODIFY BY HAND.
// 运行 dart run tool/generate_diagnostic_routes.dart 从固定 OpenAPI 更新。
const diagnosticApiRoutes = <String, String>{
  'DELETE /api/v1/mobile/devices/current': 'mobileDeviceUnregister',
  'DELETE /api/v1/users/me': 'usersDeleteMe',
  'DELETE /api/v1/users/me/avatar': 'usersRemoveAvatar',
  'DELETE /api/v1/users/me/profile-cover': 'usersRemoveProfileCover',
  'GET /api/v1/admin': 'adminIndex',
  'GET /api/v1/admin/accounts': 'adminAccountsList',
  'GET /api/v1/admin/appeals': 'adminModerationAppealsList',
  'GET /api/v1/admin/audit-logs': 'adminModerationListAuditLogs',
  'GET /api/v1/admin/audit-logs/export': 'adminModerationExportAuditLogs',
  'GET /api/v1/admin/auth/session': 'adminAuthSession',
  'GET /api/v1/admin/cases': 'moderationCasesList',
  'GET /api/v1/admin/content': 'adminContentList',
  'GET /api/v1/admin/content/hidden': 'adminModerationListHiddenContent',
  'GET /api/v1/admin/dashboard/distributions': 'adminDashboardDistributions',
  'GET /api/v1/admin/dashboard/overview': 'adminDashboardOverview',
  'GET /api/v1/admin/dashboard/timeseries': 'adminDashboardTimeseries',
  'GET /api/v1/admin/notification-campaigns': 'notificationCampaignList',
  'GET /api/v1/admin/notifications/system/history': 'adminGetHistory',
  'GET /api/v1/admin/operations/settings': 'siteOperationalSettingsGet',
  'GET /api/v1/admin/reports': 'adminReportsFindAll',
  'GET /api/v1/admin/tags': 'adminTaxonomyListTags',
  'GET /api/v1/admin/thread-categories': 'adminTaxonomyListCategories',
  'GET /api/v1/admin/users': 'adminModerationListUsers',
  'GET /api/v1/admin/users/search': 'adminSearchUsers',
  'GET /api/v1/auth/sessions': 'authListSessions',
  'GET /api/v1/bookmarks': 'bookmarksFindAll',
  'GET /api/v1/bookmarks/folders': 'bookmarksFindFolders',
  'GET /api/v1/direct-conversations': 'directConversationsFindAll',
  'GET /api/v1/direct-conversations/unread': 'directConversationsUnread',
  'GET /api/v1/drafts': 'draftsFindAll',
  'GET /api/v1/drafts/slots': 'draftsSlotUsage',
  'GET /api/v1/drafts/state': 'draftsState',
  'GET /api/v1/health': 'healthCheck',
  'GET /api/v1/image-gallery': 'galleryList',
  'GET /api/v1/meta': 'metaGetMeta',
  'GET /api/v1/moderation/decisions/mine': 'userModerationAppealsMine',
  'GET /api/v1/moments': 'momentsList',
  'GET /api/v1/moments/bookmark-folders': 'momentsBookmarkFolders',
  'GET /api/v1/moments/bookmarks': 'momentsBookmarks',
  'GET /api/v1/notifications': 'notificationsFindAll',
  'GET /api/v1/notifications/unread': 'notificationsUnreadCount',
  'GET /api/v1/search': 'searchSearch',
  'GET /api/v1/search/moments': 'searchSearchMoments',
  'GET /api/v1/search/posts': 'searchSearchPosts',
  'GET /api/v1/search/threads': 'searchSearchThreads',
  'GET /api/v1/search/users': 'searchSearchUsers',
  'GET /api/v1/stickers': 'stickersGetCollection',
  'GET /api/v1/subscriptions': 'subscriptionsFindAll',
  'GET /api/v1/tags': 'tagsSearch',
  'GET /api/v1/thread-categories': 'threadCategoriesList',
  'GET /api/v1/threads': 'threadsFindAll',
  'GET /api/v1/threads/draft': 'threadsFindDrafts',
  'GET /api/v1/users/followers': 'usersFollowFollowers',
  'GET /api/v1/users/following': 'usersFollowFollowing',
  'GET /api/v1/users/me': 'usersGetMe',
  'GET /api/v1/users/me/blocks': 'usersFollowBlocks',
  'GET /api/v1/users/me/collaborated-threads': 'usersGetMyCollaboratedThreads',
  'GET /api/v1/users/mention-candidates': 'usersMentionCandidates',
  'GET /api/v1/users/search': 'usersSearch',
  'GET /api/v1/wallet': 'economyGetWallet',
  'GET /api/v1/wallet/transactions': 'economyTransactions',
  'PATCH /api/v1/admin/operations/settings': 'siteOperationalSettingsUpdate',
  'PATCH /api/v1/users/me': 'usersUpdateMe',
  'PATCH /api/v1/users/me/avatar': 'usersSetAvatar',
  'PATCH /api/v1/users/me/profile-cover': 'usersSetProfileCover',
  'POST /api/v1/admin/accounts/invites': 'adminAccountsInvite',
  'POST /api/v1/admin/accounts/transfer-super-admin': 'adminAccountsTransfer',
  'POST /api/v1/admin/auth/challenge': 'adminAuthChallenge',
  'POST /api/v1/admin/auth/logout': 'adminAuthLogout',
  'POST /api/v1/admin/auth/step-up/challenge': 'adminAuthStepUpChallenge',
  'POST /api/v1/admin/auth/step-up/verify': 'adminAuthVerifyStepUp',
  'POST /api/v1/admin/auth/verify': 'adminAuthVerify',
  'POST /api/v1/admin/notification-campaigns': 'notificationCampaignCreate',
  'POST /api/v1/admin/notification-campaigns/preview':
      'notificationCampaignPreview',
  'POST /api/v1/admin/notifications/system': 'adminSendSystemNotification',
  'POST /api/v1/admin/notifications/system/preview': 'adminPreviewRecipients',
  'POST /api/v1/admin/tags': 'adminTaxonomyCreateTag',
  'POST /api/v1/admin/thread-categories': 'adminTaxonomyCreateCategory',
  'POST /api/v1/auth/change-email/request-code': 'authRequestChangeEmailCode',
  'POST /api/v1/auth/change-email/verify': 'authVerifyChangeEmail',
  'POST /api/v1/auth/change-password': 'authChangePassword',
  'POST /api/v1/auth/forgot-password': 'authForgotPassword',
  'POST /api/v1/auth/login': 'authLogin',
  'POST /api/v1/auth/logout': 'authLogout',
  'POST /api/v1/auth/refresh': 'authRefresh',
  'POST /api/v1/auth/register/request-code': 'authRequestCode',
  'POST /api/v1/auth/register/verify-and-complete': 'authVerifyAndComplete',
  'POST /api/v1/auth/reset-password': 'authResetPassword',
  'POST /api/v1/bookmarks': 'bookmarksCreate',
  'POST /api/v1/bookmarks/folders': 'bookmarksCreateFolder',
  'POST /api/v1/direct-conversations': 'directConversationsCreate',
  'POST /api/v1/drafts': 'draftsCreate',
  'POST /api/v1/media/upload-done': 'mediaConfirmUpload',
  'POST /api/v1/media/upload-url': 'mediaGetUploadUrl',
  'POST /api/v1/moderation/appeal-token': 'userModerationAppealsIssueToken',
  'POST /api/v1/moderation/appeals': 'userModerationAppealsAppeal',
  'POST /api/v1/moments': 'momentsCreate',
  'POST /api/v1/moments/bookmark-folders': 'momentsCreateBookmarkFolder',
  'POST /api/v1/notifications/read-all': 'notificationsMarkAllAsRead',
  'POST /api/v1/reports': 'reportsCreate',
  'POST /api/v1/stickers/imports/direct-message': 'stickersImportDirectMessage',
  'POST /api/v1/stickers/imports/media': 'stickersImportMedia',
  'POST /api/v1/stickers/imports/moment-comment-image':
      'stickersImportMomentCommentImage',
  'POST /api/v1/stickers/imports/moment-image': 'stickersImportMomentImage',
  'POST /api/v1/stickers/imports/post-image': 'stickersImportPostImage',
  'POST /api/v1/subscriptions': 'subscriptionsCreate',
  'POST /api/v1/tags': 'tagsCreate',
  'POST /api/v1/threads': 'threadsCreate',
  'POST /api/v1/wallet/check-in': 'economyCheckIn',
  'PUT /api/v1/mobile/devices/current': 'mobileDeviceRegister',
  'PUT /api/v1/stickers/reorder': 'stickersReorder',
  'DELETE /api/v1/admin/accounts/invites/{id}': 'adminAccountsCancel',
  'DELETE /api/v1/admin/accounts/{id}': 'adminAccountsRevoke',
  'DELETE /api/v1/admin/notification-campaigns/{id}':
      'notificationCampaignCancel',
  'DELETE /api/v1/auth/sessions/{id}': 'authRevokeSession',
  'DELETE /api/v1/bookmarks/folders/{id}': 'bookmarksDeleteFolder',
  'DELETE /api/v1/bookmarks/{id}': 'bookmarksRemove',
  'DELETE /api/v1/direct-messages/{id}': 'directMessagesRecall',
  'DELETE /api/v1/drafts/{id}': 'draftsRemove',
  'DELETE /api/v1/moments/bookmark-folders/{id}': 'momentsDeleteBookmarkFolder',
  'DELETE /api/v1/moments/{id}': 'momentsRemove',
  'DELETE /api/v1/moments/{id}/bookmark': 'momentsUnbookmark',
  'DELETE /api/v1/moments/{id}/like': 'momentsUnlike',
  'DELETE /api/v1/notifications/{id}': 'notificationsRemove',
  'DELETE /api/v1/posts/{id}': 'postsRemove',
  'DELETE /api/v1/posts/{id}/pin': 'postsUnpin',
  'DELETE /api/v1/stickers/{favoriteId}': 'stickersRemove',
  'DELETE /api/v1/subscriptions/{id}': 'subscriptionsRemove',
  'DELETE /api/v1/subthreads/{id}': 'subthreadsRemove',
  'DELETE /api/v1/threads/{id}': 'threadsRemove',
  'DELETE /api/v1/threads/{id}/like': 'threadsUnlike',
  'DELETE /api/v1/threads/{threadId}/members/me': 'threadMembersExitMember',
  'DELETE /api/v1/users/follow/{id}': 'usersFollowUnfollow',
  'DELETE /api/v1/users/me/block/{id}': 'usersFollowUnblock',
  'DELETE /api/v1/users/me/followers/{id}': 'usersFollowRemoveFollower',
  'GET /api/v1/admin/cases/{id}': 'moderationCasesGet',
  'GET /api/v1/admin/reports/{id}': 'adminReportsFindOne',
  'GET /api/v1/admin/users/{id}': 'adminModerationGetUser',
  'GET /api/v1/direct-conversations/by-user/{userId}':
      'directConversationsFindByUser',
  'GET /api/v1/direct-conversations/{id}': 'directConversationsFindById',
  'GET /api/v1/direct-conversations/{id}/messages':
      'directConversationsMessages',
  'GET /api/v1/drafts/{id}': 'draftsFindById',
  'GET /api/v1/media/{id}': 'mediaGetMedia',
  'GET /api/v1/moments/{id}': 'momentsDetail',
  'GET /api/v1/moments/{id}/comment-authors': 'momentsCommentAuthors',
  'GET /api/v1/moments/{id}/comments': 'momentsCommentsList',
  'GET /api/v1/posts/{id}': 'postsFindById',
  'GET /api/v1/posts/{id}/replies': 'postsFindReplies',
  'GET /api/v1/posts/{id}/replies/authors': 'postsFindReplyAuthors',
  'GET /api/v1/stickers/imports/{id}': 'stickersGetImport',
  'GET /api/v1/subthreads/{id}': 'subthreadsFindById',
  'GET /api/v1/subthreads/{subthreadId}/posts': 'postsFindFloors',
  'GET /api/v1/subthreads/{subthreadId}/posts/authors': 'postsFindFloorAuthors',
  'GET /api/v1/tags/{id}': 'tagsGetById',
  'GET /api/v1/threads/join-by-link/{token}': 'threadsPreviewInviteLink',
  'GET /api/v1/threads/{id}': 'threadsFindById',
  'GET /api/v1/threads/{threadId}/members': 'threadMembersFindAll',
  'GET /api/v1/threads/{threadId}/posts/latest': 'postsFindLatestInThread',
  'GET /api/v1/threads/{threadId}/search/posts': 'threadSearchSearchPosts',
  'GET /api/v1/threads/{threadId}/subthreads': 'subthreadsFindAll',
  'GET /api/v1/threads/{threadId}/tags': 'threadTagsFindAll',
  'GET /api/v1/users/{id}': 'usersGetUser',
  'GET /api/v1/users/{id}/activity-summary': 'usersGetUserActivitySummary',
  'GET /api/v1/users/{id}/bookmarks': 'usersGetUserBookmarks',
  'GET /api/v1/users/{id}/created-threads': 'usersGetUserCreatedThreads',
  'GET /api/v1/users/{id}/followers': 'usersFollowUserFollowers',
  'GET /api/v1/users/{id}/following': 'usersFollowUserFollowing',
  'GET /api/v1/users/{id}/moment-bookmarks': 'usersGetUserMomentBookmarks',
  'GET /api/v1/users/{id}/moments': 'userMomentsList',
  'GET /api/v1/users/{id}/played-threads': 'usersGetUserPlayedThreads',
  'GET /api/v1/users/{id}/recent-replies': 'usersGetUserRecentReplies',
  'PATCH /api/v1/admin/content/thread/{id}/taxonomy':
      'adminContentUpdateTaxonomy',
  'PATCH /api/v1/admin/tags/{id}': 'adminTaxonomyUpdateTag',
  'PATCH /api/v1/admin/thread-categories/{id}': 'adminTaxonomyUpdateCategory',
  'PATCH /api/v1/admin/users/{id}/role': 'adminModerationUpdateRole',
  'PATCH /api/v1/bookmarks/folders/{id}': 'bookmarksRenameFolder',
  'PATCH /api/v1/bookmarks/{id}': 'bookmarksMove',
  'PATCH /api/v1/direct-conversations/{id}/archive':
      'directConversationsArchive',
  'PATCH /api/v1/direct-conversations/{id}/request':
      'directConversationsHandleRequest',
  'PATCH /api/v1/drafts/{id}': 'draftsUpdate',
  'PATCH /api/v1/moments/bookmark-folders/{id}': 'momentsRenameBookmarkFolder',
  'PATCH /api/v1/moments/{id}': 'momentsUpdate',
  'PATCH /api/v1/moments/{id}/bookmark': 'momentsMoveBookmark',
  'PATCH /api/v1/notifications/{id}': 'notificationsSetReadStatus',
  'PATCH /api/v1/posts/{id}': 'postsUpdate',
  'PATCH /api/v1/subthreads/{id}': 'subthreadsUpdate',
  'PATCH /api/v1/threads/{id}': 'threadsUpdate',
  'PATCH /api/v1/threads/{id}/aggregate': 'threadsSaveAggregate',
  'POST /api/v1/admin-invitations/{token}/accept':
      'adminInviteAcceptanceAccept',
  'POST /api/v1/admin/appeals/{id}/resolve': 'adminModerationAppealsResolve',
  'POST /api/v1/admin/cases/{id}/resolve': 'moderationCasesResolve',
  'POST /api/v1/admin/reports/{id}/resolve': 'adminReportsResolve',
  'POST /api/v1/admin/users/{id}/sanctions': 'adminModerationSanctionUser',
  'POST /api/v1/admin/users/{id}/sanctions/current/revoke':
      'adminModerationRevokeSanction',
  'POST /api/v1/direct-conversations/{id}/messages': 'directConversationsSend',
  'POST /api/v1/direct-conversations/{id}/read': 'directConversationsMarkRead',
  'POST /api/v1/media/{id}/upload-url': 'mediaReissueUploadUrl',
  'POST /api/v1/moments/{id}/bookmark': 'momentsBookmark',
  'POST /api/v1/moments/{id}/comments': 'momentsCreateComment',
  'POST /api/v1/moments/{id}/like': 'momentsLike',
  'POST /api/v1/moments/{id}/tips': 'economyTipMoment',
  'POST /api/v1/posts/{id}/pin': 'postsPin',
  'POST /api/v1/subthreads/{subthreadId}/posts': 'postsCreate',
  'POST /api/v1/threads/join-by-link/{token}': 'threadsJoinByInviteLink',
  'POST /api/v1/threads/{id}/export': 'threadsExport',
  'POST /api/v1/threads/{id}/invite-link': 'threadsCreateInviteLink',
  'POST /api/v1/threads/{id}/like': 'threadsLike',
  'POST /api/v1/threads/{id}/tips': 'economyTipThread',
  'POST /api/v1/threads/{threadId}/members/join': 'threadMembersJoin',
  'POST /api/v1/threads/{threadId}/subthreads': 'subthreadsCreate',
  'POST /api/v1/threads/{threadId}/tags': 'threadTagsAdd',
  'POST /api/v1/users/follow/{id}': 'usersFollowFollow',
  'POST /api/v1/users/me/block/{id}': 'usersFollowBlock',
  'POST /api/v1/users/{id}/tips': 'economyTipUser',
  'PUT /api/v1/subthreads/{subthreadId}/body': 'postsUpsertBody',
  'PUT /api/v1/threads/{threadId}/subthreads/reorder': 'subthreadsReorder',
  'DELETE /api/v1/moments/{id}/comments/{commentId}': 'momentsRemoveComment',
  'DELETE /api/v1/threads/{threadId}/tags/{tagId}': 'threadTagsRemove',
  'GET /api/v1/admin/content/{type}/{id}': 'adminContentDetail',
  'GET /api/v1/moments/{id}/comments/{commentId}/context':
      'momentsCommentContext',
  'GET /api/v1/moments/{id}/comments/{commentId}/replies': 'momentsReplies',
  'PATCH /api/v1/threads/{threadId}/members/{userId}':
      'threadMembersUpdateMember',
  'POST /api/v1/admin/content/{type}/{id}/hide': 'adminModerationHideContent',
  'POST /api/v1/admin/content/{type}/{id}/restore':
      'adminModerationRestoreContent',
  'POST /api/v1/moderation/content/{type}/{id}/hide':
      'clientContentModerationHide',
};
